### ISSUE TITLE
Freeze Charging

### ISSUE THREAD

**Issue by fboundy** [springfall2008/batpred#299]
Hi Trefor

Trying to get my head around Freeze Charging. Two scenarios:

1. What is the desired behaviour when:

Current SOC is 30%
Target SOC is set to 15%
Status is Freeze Charging
PV is 2kW

Export is 15p and Import is 20p

2. Same conditions as above but at night so no PV

Thanks

**Comment by fboundy** [comment]
And a follow-up: Why would you ever turn off `Set Soc Enable`?

**Comment by springfall2008** [comment]
Freeze charging is just a shortcut for hold the current battery charge level, this means excess solar would charge the battery but excess demand is from the grid. The cloud simulation is meant to stop it accidentally importing due to clouds in this scenario.

set soC enable when off means you can manually set it yourself but leave predbat to calculate the windows
