### ISSUE TITLE
Pulling from Grid unnessarily 

### ISSUE THREAD

**Issue by b1nuzz** [springfall2008/batpred#577]
**Describe the bug**
Pulling from the grid when everything points to battery usage would be OK. 

PredBat up to date

[appdaemon.log](https://github.com/springfall2008/batpred/files/13830518/appdaemon.log)
![Screenshot 2024-01-04 135453](https://github.com/springfall2008/batpred/assets/61235761/c849b1d8-339b-4312-8629-937a9e007278)
![Screenshot 2024-01-04 135327](https://github.com/springfall2008/batpred/assets/61235761/5da7cd8d-3042-4a6e-a040-e29652b8b6d9)
![Screenshot 2024-01-04 135305](https://github.com/springfall2008/batpred/assets/61235761/c2850682-e6ed-45c6-b439-2ad1f1fd87a0)
![Screenshot 2024-01-04 091452](https://github.com/springfall2008/batpred/assets/61235761/948f1f83-0727-4acb-984b-e92fc28a2a1c)

**Comment by springfall2008** [comment]
I think there are two things here:

1. Your timeouts in the log are probably as you have the run loop time for GivTCP set too fast, can try changing it to maybe 20 seconds in your GivTCP settings?

2. The plan above looks okay but probably not idea due to round trip losses, if you try to turn off 'combine charge' then I think it will get better.

**Comment by springfall2008** [comment]
Can you also try this release: 

https://github.com/springfall2008/batpred/releases/tag/v7.14.32

And make sure set_reserve_enable is true

**Comment by b1nuzz** [comment]
Thanks. 
I have actioned all of the above. 
Immediately the battery prediction looks more like it used to, with overnight charges and daily useage. 

Will run like this for 24/48 hours and report back.

**Comment by springfall2008** [comment]
Please reopen if you have a new issue
