### ISSUE TITLE
HACS reports incorrect predbat version

### ISSUE THREAD

**Issue by KeithB** [springfall2008/batpred#759]
**Describe the bug**
Since the ability to update by the updates selector in HA, HACS has become confused and reports the wrong version. First couple of updates on the 7.14.x stream seemed OK but since 7.14.22 HACS does not pick up that the new version is running.

Updates via the selector are successful and confirmed directly from appdaemon logs and checking the predbat.py script directly.

**Expected behavior**
HACS correctly reports the installed predbat version

**Predbat version**
Current version is v7.15.21. HACS reports 7.14.22.

**Environment details**
- HA is a Docker install with appdaemon running as a separate container.
- predbat is a custom appdaemon repository in HACS
- Current predbat install is v7.15.21(first install September/October '23 and then updated regularly since then - no clean re-install done)

**Screenshots**
![image](https://github.com/springfall2008/batpred/assets/1209043/46b83ffd-cb0c-4538-a519-ba8f3918c0c4)
![image](https://github.com/springfall2008/batpred/assets/1209043/8ff858a8-aca3-4144-96ed-3a32499b7682)

**Log file**
Not sure which logs would be most useful here. Probably don't have the logs available from when it first started but can get logs from todays update to v7.15.21.

**Comment by gcoan** [comment]
I have exactly the same problem with a HAOS install and HACS running as an add-on.  It doesn’t seem to recognise that Predbat has been updated - giving me the message “You are running version 7.15.4, version 7.15.21 is available”On 14 Feb 2024, at 18:29, KeithB ***@***.***> wrote:﻿
Describe the bug
Since the ability to update by the updates selector in HA, HACS has become confused and reports the wrong version. First couple of updates on the 7.14.x stream seemed OK but since 7.14.22 HACS does not pick up that the new version is running.
Updates via the selector are successful and confirmed directly from appdaemon logs and checking the predbat.py script directly.
Expected behavior
HACS correctly reports the installed predbat version
Predbat version
Current version is v7.15.21. HACS reports 7.14.22.
Environment details

HA is a Docker install with appdaemon running as a separate container.
predbat is a custom appdaemon repository in HACS
Current predbat install is v7.15.21(first install September/October '23 and then updated regularly since then - no clean re-install done)

Screenshots
image.png (view on web)
image.png (view on web)
Log file
Not sure which logs would be most useful here. Probably don't have the logs available from when it first started but can get logs from todays update to v7.15.21.

**Comment by gcoan** [comment]
I have exactly the same problem with a HAOS install and HACS running as an add-on.  It doesn’t seem to recognise that Predbat has been updated

**Comment by springfall2008** [comment]
HACS is now depricated
